name: Benzin ğŸ”¥

on:
  push:
    branches:
      - v2
  pull_request:
    branches:
      - v2
permissions:
  contents: write
jobs:
  build:
    name: Build & Deploy Standalone Benzin
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    environment: benzin
    steps:
      - name: Checkout code ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Setup Environment
        uses: ./github/workflows/setup.yml

      - name: Build project ğŸ› ï¸
        env:
          REACT_APP_PIMLICO_API_KEY: ${{ secrets.REACT_APP_PIMLICO_API_KEY }}
          REACT_APP_JIFFYSCAN_API_KEY: ${{ secrets.REACT_APP_JIFFYSCAN_API_KEY }}
          RELAYER_URL: ${{ vars.RELAYER_URL }}
        run: yarn build:web:benzin

      - name: Deploy ğŸš€ğŸŒ•
        if: github.ref == 'refs/heads/v2'
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: build/benzin-prod
          cname: benzin.ambire.com
