name: Benzin ğŸ”¥

on:
  push:
    branches:
      - v2
  pull_request:
    branches:
      - v2
permissions:
  contents: write
jobs:
  build:
    name: Build & Deploy Standalone Benzin
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    environment: benzin
    steps:
      - name: Checkout code ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Add SSH key to checkout a private repo
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Checkout code ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Git submodules init
        run: git submodule init
        shell: bash

      - name: Git submodules update
        run: git submodule update
        shell: bash

      - name: Build project ğŸ› ï¸
        env:
          REACT_APP_PIMLICO_API_KEY: ${{ vars.REACT_APP_PIMLICO_API_KEY }}
          REACT_APP_ETHERSPOT_API_KEY: ${{ vars.REACT_APP_ETHERSPOT_API_KEY }}
          RELAYER_URL: ${{ vars.RELAYER_URL }}
        run: yarn build:web:benzin

      - name: Deploy ğŸš€ğŸŒ•
        if: github.ref == 'refs/heads/v2'
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: build/benzin-prod
          cname: explorer.ambire.com
