name: E2E Playwright Tests

on:
  push:
    branches:
      - v2
      - main
  pull_request:
    types: ['ready_for_review', 'synchronize']
    branches:
      - v2
      - main
  workflow_dispatch:

jobs:
  e2e-tests:
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    environment: testing

    env:
      IS_TESTING: 'true'
      E2E_DEBUG: ${{ vars.E2E_DEBUG }}
      # DISPLAY: ':99.0'
      RELAYER_URL: ${{ vars.RELAYER_URL }}
      VELCRO_URL: ${{ vars.VELCRO_URL }}
      LI_FI_API_KEY: ${{ vars.LI_FI_API_KEY }}
      BUNGEE_API_KEY: ${{ vars.BUNGEE_API_KEY }}
      REACT_APP_PIMLICO_API_KEY: ${{ vars.REACT_APP_PIMLICO_API_KEY }}
      REACT_APP_ETHERSPOT_API_KEY: ${{ vars.REACT_APP_ETHERSPOT_API_KEY }}
      REACT_APP_CANDIDE_API_KEY: ${{ vars.REACT_APP_CANDIDE_API_KEY }}
      KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
      SEED: ${{ secrets.SEED }}
      BA_PRIVATE_KEY: ${{ secrets.BA_PRIVATE_KEY }}
      BA_PASSPHRASE: ${{ secrets.BA_PASSPHRASE }}
      BA_ACCOUNTS: ${{ vars.BA_ACCOUNTS }}
      BA_KEYSTORE_UID: ${{ vars.BA_KEYSTORE_UID }}
      BA_KEYS: ${{ vars.BA_KEYS }}
      BA_SECRETS: ${{ secrets.BA_SECRETS }}
      BA_SEEDS: ${{ vars.BA_SEEDS }}
      BA_NETWORK_WITH_ASSETS: ${{ vars.BA_NETWORK_WITH_ASSETS }}
      BA_NETWORK_WITH_POSITIONS: ${{ vars.BA_NETWORK_WITH_POSITIONS }}
      BA_ONBOARDING_STATE: ${{ vars.BA_ONBOARDING_STATE }}
      BA_PREVIOUSHINTS: ${{ vars.BA_PREVIOUSHINTS }}
      BA_SELECTED_ACCOUNT: ${{ vars.BA_SELECTED_ACCOUNT }}
      BA_TERMSTATE: ${{ vars.BA_TERMSTATE }}
      SA_ACCOUNTS: ${{ vars.SA_ACCOUNTS }}
      SA_ACCOUNT_JSON: ${{ secrets.SA_ACCOUNT_JSON }}
      SA_IS_ONBOARDED: ${{ vars.SA_IS_ONBOARDED }}
      SA_KEYSTORE_UID: ${{ vars.SA_KEYSTORE_UID }}
      SA_KEYS: ${{ vars.SA_KEYS }}
      SA_SECRETS: ${{ secrets.SA_SECRETS }}
      SA_SEEDS: ${{ vars.SA_SEEDS }}
      SA_ONBOARDING_STATE: ${{ vars.SA_ONBOARDING_STATE }}
      SA_PREVIOUSHINTS: ${{ vars.SA_PREVIOUSHINTS }}
      SA_SELECTED_ACCOUNT: ${{ vars.SA_SELECTED_ACCOUNT }}
      SA_TERMSTATE: ${{ vars.SA_TERMSTATE }}
      SA_NETWORK_WITH_ASSETS: ${{ vars.SA_NETWORK_WITH_ASSETS }}
      SA_NETWORK_WITH_POSITIONS: ${{ vars.SA_NETWORK_WITH_POSITIONS }}
      SA_PASSPHRASE: ${{ secrets.SA_PASSPHRASE }}
      DEFAULT_INVITATION_CODE_DEV: ${{ vars.DEFAULT_INVITATION_CODE_DEV }}
      SEED_24_WORDS: ${{ secrets.SEED_24_WORDS }}
      SHOULD_RUN_TREZOR_TESTS: 'true'
      PLAYWRIGHT_SKIP_GIT_METADATA: '1' # Optional fix to avoid Git fetch timeout
      # Enables Playwright to intercept network requests initiated by Service Workers.
      # We use it to mock or block background requests that can't be intercepted via page.route().
      PW_EXPERIMENTAL_SERVICE_WORKER_NETWORK_EVENTS: '1'

    steps:
      - name: Checkout full Git history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fixes GitCommitInfo timeout

      - name: Add SSH key to checkout a private repo
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Git submodules init
        run: git submodule init
        shell: bash

      - name: Git submodules update
        run: git submodule update
        shell: bash

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0

      - name: Install root dependencies
        run: yarn install --frozen-lockfile
        shell: bash

      - name: Build webkit extension
        run: yarn build:web:webkit

      - name: Start trezor-emulator container
        run: |
          docker pull ghcr.io/trezor/trezor-user-env
          docker compose -f ./docker-compose-mac.yml up --force-recreate -d

      - name: Install e2e test dependencies
        working-directory: ./e2e-playwright-tests
        run: npm ci

      - name: Install Playwright browsers
        working-directory: ./e2e-playwright-tests
        run: npx playwright install --with-deps chromium

      - name: Run Balance Check test for SA and BA
        working-directory: ./e2e-playwright-tests
        run: npm run balance:test

      - name: Run Playwright tests
        working-directory: ./e2e-playwright-tests
        run: npm run test

      - name: Upload HTML report
        if: always()
        working-directory: ./e2e-playwright-tests
        run: |
          mkdir -p playwright-report
          zip -r playwright-report.zip playwright-report
        continue-on-error: true

      - name: Save test report as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: ./e2e-playwright-tests/playwright-report.zip
